#version 460 core

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer InstanceData {
    mat4 instances[];
};

layout(std430, binding = 1) buffer VisibleInstances {
    uint visibleCount;
    mat4 visibleInstances[];
};

void main() {
    uint id = gl_GlobalInvocationID.x;

    uint count = atomicAdd(visibleCount, 1);
    visibleInstances[count] = instances[id];
}